DROP TABLE IF EXISTS bio_sample ;
CREATE TABLE bio_sample(
sample_id tinyint(2) not null,
description varchar(40),
KEY sample_id_idx (sample_id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS seq_read ;
CREATE TABLE seq_read (
sample_id tinyint(2) NOT NULL,
chromosome_id tinyint(2) NOT NULL,
start int(10) NOT NULL,
rend int(10) NOT NULL,
strand tinyint(2) NOT NULL
) 
PARTITION BY RANGE (chromosome_id)

(
PARTITION chr0 VALUES LESS THAN (1),
PARTITION chr1 VALUES LESS THAN (2),
 PARTITION chr2 VALUES LESS THAN (3),
 PARTITION chr3 VALUES LESS THAN (4),
 PARTITION chr4 VALUES LESS THAN (5),
 PARTITION chr5 VALUES LESS THAN (6) ,
 PARTITION chr6 VALUES LESS THAN (7) ,
 PARTITION chr7 VALUES LESS THAN (8) ,
 PARTITION chr8 VALUES LESS THAN (9) ,
 PARTITION chr9 VALUES LESS THAN (10) ,
 PARTITION chr10 VALUES LESS THAN (11),
 PARTITION chr11 VALUES LESS THAN (12) ,
 PARTITION chr12 VALUES LESS THAN (13) ,
 PARTITION chr13 VALUES LESS THAN (14) ,
 PARTITION chr14 VALUES LESS THAN (15) ,
 PARTITION chr15 VALUES LESS THAN (16) ,
 PARTITION chr16 VALUES LESS THAN (17) ,
 PARTITION chr17 VALUES LESS THAN (18) ,
 PARTITION chr18 VALUES LESS THAN (19) ,
 PARTITION chr19 VALUES LESS THAN (20) ,
 PARTITION chr20 VALUES LESS THAN (21) ,
 PARTITION chr21 VALUES LESS THAN (22) ,
 PARTITION chr22 VALUES LESS THAN (23),
PARTITION chr23 VALUES LESS THAN (24), 
PARTITION chr24 VALUES LESS THAN (25),
PARTITION chr25 VALUES LESS THAN (26),
PARTITION chr30 VALUES LESS THAN (31)
);
 


